<?php

namespace App\Observers;

use App\Domain\Absence\Enums\AbsenceRequestStatus;
use App\Models\AbsenceRequest;
use App\Models\Attendance;
use Carbon\CarbonPeriod;
use Illuminate\Support\Facades\Log;

class AbsenceRequestObserver
{
    /**
     * Handle the AbsenceRequest "updated" event.
     *
     * When a request is approved, automatically upsert attendance records
     * for each date in the approved range. Only fill dates that don't already
     * have a physical check-in (rfid or manual), to avoid overwriting real presence.
     *
     * If the request is later rejected (was previously approved), the observer
     * will remove the auto-generated attendance records that have no physical
     * check-in.
     */
    public function updated(AbsenceRequest $absenceRequest): void
    {
        // Only react if the status field actually changed
        if (! $absenceRequest->wasChanged('status')) {
            return;
        }

        $newStatus = $absenceRequest->status;

        if ($newStatus === AbsenceRequestStatus::Approved) {
            $this->syncApproved($absenceRequest);
        } elseif ($newStatus === AbsenceRequestStatus::Rejected) {
            $this->rollbackAutoGenerated($absenceRequest);
        }
    }

    // ──────────────────────────────────────────────
    // Private helpers
    // ──────────────────────────────────────────────

    /**
     * Create / update attendance records for all dates in the approved range.
     */
    private function syncApproved(AbsenceRequest $absenceRequest): void
    {
        $student  = $absenceRequest->user;
        $classroom = $student?->classrooms()->where('classrooms.is_active', true)->first();

        if (! $student || ! $classroom) {
            Log::warning('[AbsenceObserver] Cannot sync: student or classroom not found.', [
                'absence_request_id' => $absenceRequest->id,
            ]);
            return;
        }

        $targetStatus = $absenceRequest->type->toAttendanceStatus();

        $period = CarbonPeriod::create($absenceRequest->date_start, $absenceRequest->date_end);

        foreach ($period as $date) {
            $dateStr = $date->toDateString();

            // Check if an attendance already exists with a physical check-in.
            // If so: NEVER overwrite — real presence beats a paper excuse.
            $existing = Attendance::where('user_id', $student->id)
                ->whereDate('date', $dateStr)
                ->first();

            if ($existing && $existing->hasCheckedIn()) {
                // Also skip if already set to the correct absence status
                Log::info('[AbsenceObserver] Skipping {date} for user {user}: physical check-in exists.', [
                    'date' => $dateStr,
                    'user' => $student->id,
                ]);
                continue;
            }

            // Upsert: create if missing, update if it was a pure absence record
            Attendance::updateOrCreate(
                ['user_id' => $student->id, 'date' => $dateStr],
                [
                    'classroom_id' => $classroom->id,
                    'status'       => $targetStatus,
                    // Deliberately leave check_in_at null so we know this was
                    // system-generated (not a real RFID scan).
                    'override_note' => "Auto-sync dari surat izin #{$absenceRequest->id}",
                ]
            );
        }
    }

    /**
     * When an absence request is rejected (possibly after being approved),
     * remove attendance records that were auto-generated by this observer
     * and have no physical check-in.
     */
    private function rollbackAutoGenerated(AbsenceRequest $absenceRequest): void
    {
        $student = $absenceRequest->user;
        if (! $student) {
            return;
        }

        $period = CarbonPeriod::create($absenceRequest->date_start, $absenceRequest->date_end);

        foreach ($period as $date) {
            $dateStr = $date->toDateString();

            Attendance::where('user_id', $student->id)
                ->whereDate('date', $dateStr)
                ->whereNull('check_in_at')  // only auto-generated records
                ->where('override_note', 'like', "%surat izin #{$absenceRequest->id}%")
                ->delete();
        }
    }
}
